name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'backend/**' ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v1.x
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Start Supabase local development setup
      run: supabase start
    
    - name: Run unit tests
      run: npm run test || echo "Tests not yet implemented"
      continue-on-error: true
      env:
        SUPABASE_URL: http://127.0.0.1:54321
        SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
        SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
        ANTHROPIC_API_KEY: mock-key-for-testing
    
    - name: Run integration tests
      run: npm run test:integration || echo "Integration tests not yet implemented"
      continue-on-error: true
      env:
        RUN_INTEGRATION_TESTS: true
        SUPABASE_URL: http://127.0.0.1:54321
        SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
        SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
        ANTHROPIC_API_KEY: mock-key-for-testing

    - name: Generate test coverage
      run: npm run test:coverage || echo "Coverage not yet implemented"
      continue-on-error: true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./backend/tests/coverage/lcov.info
        directory: ./backend/tests/coverage
        flags: backend
        name: backend-coverage
      continue-on-error: true
    
    - name: Stop Supabase
      run: supabase stop
      if: always()

  lint:
    name: Lint Backend Code
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v1.x
    
    - name: Lint TypeScript files
      run: deno lint supabase/functions/ || echo "Linting has warnings"
      continue-on-error: true

    - name: Check TypeScript formatting
      run: deno fmt --check supabase/functions/ || echo "Formatting has issues"
      continue-on-error: true

    - name: Type check
      run: deno check supabase/functions/**/*.ts || echo "Type checking has issues"
      continue-on-error: true